### PR TITLE
Remove detect-or-install-riscv-toolchain.sh

### PR DESCRIPTION
**Pull request by jarkkojs**
Left-overs from #184.

### CODE REVIEW

**Comment by jarkkojs** [comment]
@koute Need help/tips on how to fix "Rust / pallet-revive-tests (pull_request)" (no rush).

**Comment by koute** [comment]
> @koute Need help/tips on how to fix "Rust / pallet-revive-tests (pull_request)" (no rush).

You (or someone else) have to update the build scripts and the toolchain in `polkadot-sdk`, then update the pallet revive test script here to pull with the new commit hash to pull in that new code.

**Comment by jarkkojs** [comment]
> > @koute Need help/tips on how to fix "Rust / pallet-revive-tests (pull_request)" (no rush).
> 
> You (or someone else) have to update the build scripts and the toolchain in `polkadot-sdk`, then update the pallet revive test script here to pull with the new commit hash to pull in that new code.

OK, let's sync on Monday.

**Comment by athei** [comment]
We are talking about the build script for test fixtures, right?

**Comment by jarkkojs** [comment]
> We are talking about the build script for test fixtures, right?

Not sure what you are talking about.

> > > @koute Need help/tips on how to fix "Rust / pallet-revive-tests (pull_request)" (no rush).
> > 
> > 
> > You (or someone else) have to update the build scripts and the toolchain in `polkadot-sdk`, then update the pallet revive test script here to pull with the new commit hash to pull in that new code.
> 
> OK, let's sync on Monday.

```bash
$ git --no-pager grep  riscv32ema
substrate/frame/revive/fixtures/build.rs:				"--target=riscv32ema-unknown-none-elf",
substrate/frame/revive/fixtures/build.rs:				&build_dir.join("target/riscv32ema-unknown-none-elf/release").join(entry.name()),
substrate/utils/wasm-builder/src/lib.rs:		target_list.contains("riscv32ema-unknown-none-elf")
substrate/utils/wasm-builder/src/lib.rs:			RuntimeTarget::Riscv => "riscv32ema-unknown-none-elf",
```

Questions:

1. Where `riscv32emac-unknown-none-polkavm.json` should be placed in the directory tree?
2. How to pass `--target riscv32emac-unknown-none-polkavm.json`?

**Comment by koute** [comment]
@jarkkojs 

>     1. Where `riscv32emac-unknown-none-polkavm.json` should be placed in the directory tree?

Hm, probably somewhere relative to the `build.rs`? (So that the crate is standalone.)

>     2. How to pass `--target riscv32emac-unknown-none-polkavm.json`?

Modify `build.rs`. See where `--target` is passed and replace the triplet with the path to the JSON.

> $ git --no-pager grep  riscv32ema

The priority is changing it in `substrate/frame/revive/fixtures` (that's used for smart contracts). You could also do it in `substrate/utils/wasm-builder`, but for that you'll probably have to also update the polkavm executor in `substrate/client/executor/polkavm` (which, to be fair, shouldn't be too hard).

(Background: Polkadot currently runs on WASM; some time ago I've added an experimental PolkaVM-based executor where you can run the runtime under PolkaVM instead of under Wasmtime. The code in `wasm-builder` is used to build the runtime for running under PolkaVM. This code is not used in production and is pretty much experimental, but we will need it once we'll be migrating to JAM.)

**Comment by athei** [comment]
> > We are talking about the build script for test fixtures, right?
> 
> ```
> error: override toolchain 'riscv32em-nightly-2024-01-05-r0-x86_64-unknown-linux-gnu' is not installed: the RUSTUP_TOOLCHAIN environment variable specifies an uninstalled toolchain
> ```

This has to be fixed in `pallet-contracts-fixtures`. I will do a PR.

**Comment by athei** [comment]
Fixed by https://github.com/paritytech/polkadot-sdk/pull/6266

**Comment by jarkkojs** [comment]
@koute, @athei:

```
error: failed to run custom build command for `pallet-revive-fixtures v0.1.0 (/home/runner/work/polkavm/polkavm/target/test-pallet-revive/polkadot-sdk/substrate/frame/revive/fixtures)`
Caused by:
  process didn't exit successfully: `/home/runner/work/polkavm/polkavm/target/test-pallet-revive/polkadot-sdk/target/debug/build/pallet-revive-fixtures-0ad3767b3ce8a461/build-script-build` (exit status: 1)
  --- stdout
  cargo::rerun-if-env-changed=PALLET_REVIVE_FIXTURES_RUSTUP_TOOLCHAIN
  cargo::rerun-if-env-changed=PALLET_REVIVE_FIXTURES_STRIP
  cargo::rerun-if-env-changed=PALLET_REVIVE_FIXTURES_OPTIMIZE
  cargo::rerun-if-changed=/home/runner/work/polkavm/polkavm/target/test-pallet-revive/polkadot-sdk/substrate/frame/revive/fixtures
  cargo::rerun-if-changed=/home/runner/work/polkavm/polkavm/target/test-pallet-revive/polkadot-sdk/substrate/frame/revive/uapi
  --- stderr
  error: process didn't exit successfully: `rustc -vV` (exit status: 1)
  --- stderr
  error: override toolchain 'riscv32em-nightly-2024-01-05-r0-x86_64-unknown-linux-gnu' is not installed: the RUSTUP_TOOLCHAIN environment variable specifies an uninstalled toolchain
  Error: Failed to build contracts
warning: build failed, waiting for other jobs to finish...
Error: Process completed with exit code 101.
```

This is after updating the commit ID in `ci/jobs/build-and-test-pallet-revive.sh`. Unfortunately most of the day went on re-configuring OpenPGP to be compatible with this new work (but it is one thing that is better to do with care, caution and offline).

Anyway, I just put this transcript of the test here for commentary, tips and remarks.

**Comment by athei** [comment]
I assume somewhere you are setting `PALLET_REVIVE_FIXTURES_RUSTUP_TOOLCHAIN` to `riscv32em-nightly-2024-01-05-r0-x86_64-unknown-linux-gnu`. This has to be removed.

**Pull request closed without merging**
